name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obligatorio para que SonarQube analice el historial correctamente

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven, Test and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Proporcionado por GitHub automáticamente
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # El secret que acabamos de crear
        # El comando 'verify' ejecuta los tests y JaCoCo. Luego el plugin de Sonar envía los datos.
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.projectKey=carrillitoo_Proyecto_PDS 
          -Dsonar.organization=carrillitoo
          -Dsonar.host.url=https://sonarcloud.io 
